### ISSUE TITLE
add config option to clear console

### ISSUE THREAD

**Issue by joernroeder** [vue-a11y/vue-axe#3]
currently console gets cleared on `updated` via `clearAxeConsole` which means that everything you log in `mounted()` lifecycle hook will never show up in the console.

**Comment by ktquez** [comment]
@joernroeder 
Thanks to @MechJosh0 PR this problem has been solved, you can check in [v1.0.7](https://github.com/vue-a11y/vue-axe/tree/v1.0.7).

@MechJosh0  sorry for the delay to merge. 

I sent you a message on Twitter.

**Comment by ianaya89** [comment]
Hi, I am still facing this issue in version `1.0.7`. Is there any way to disable console clear?

<img width="1282" alt="Screen Shot 2020-01-20 at 18 05 11" src="https://user-images.githubusercontent.com/3258966/72757746-8aab0200-3baf-11ea-9746-dd6401376eca.png">
